//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MplProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class attendence
    {
        public int id { get; set; }
        public System.DateTime date { get; set; }
        public string aattendence { get; set; }
        public int emp_id { get; set; }
    
        public virtual empLogin empLogin { get; set; }
    }
}
