//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MplProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bill
    {
        public int serial_no { get; set; }
        public int cus_id { get; set; }
        public int pro_id { get; set; }
        public int quantity { get; set; }
        public int price { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual product product { get; set; }
    }
}
