//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MplProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CheckAndBalanceEntities : DbContext
    {
        public CheckAndBalanceEntities()
            : base("name=CheckAndBalanceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<attendence> attendences { get; set; }
        public virtual DbSet<bill> bills { get; set; }
        public virtual DbSet<booking_engine> booking_engine { get; set; }
        public virtual DbSet<company_details> company_details { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<empLogin> empLogins { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<manager> managers { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<payment> payments { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<signup> signups { get; set; }
    }
}
