//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MplProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int order_id { get; set; }
        public string status { get; set; }
        public System.DateTime order_date { get; set; }
        public System.DateTime sending_date { get; set; }
        public System.DateTime receving_date { get; set; }
        public int no_of_order { get; set; }
        public int product_id { get; set; }
        public int cus_id { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual product product { get; set; }
    }
}
