//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MplProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int order_id { get; set; }
        public string status { get; set; }
        public Nullable<int> order_date { get; set; }
        public Nullable<int> sending_date { get; set; }
        public Nullable<int> receving_date { get; set; }
        public Nullable<int> product_id { get; set; }
        public string cus_id { get; set; }
    
        public virtual product product { get; set; }
    }
}
